import { SYMBOLS } from "./symbols";
export const booleanAttributes = [
  'checked',
  'readonly',
  'autoplay',
  'allowfullscreen',
  'async',
  'autofocus',
  'autoplay',
  'controls',
  'default',
  'defer',
  'disabled',
  'formnovalidate',
  'inert',
  'ismap',
  'itemscope',
  'loop',
  'multiple',
  'muted',
  'nomodule',
  'novalidate',
  'open',
  'playsinline',
  'required',
  'reversed',
  'selected',
];

export const propertyKeys = [
  'class',
  'shadowrootmode',
  // boolean attributes (https://meiert.com/en/blog/boolean-attributes-of-html/)
  'checked',
  'readonly',
  'value',
  'autoplay',
  'allowfullscreen',
  'async',
  'autofocus',
  'autoplay',
  'controls',
  'default',
  'defer',
  'disabled',
  'formnovalidate',
  'inert',
  'ismap',
  'itemscope',
  'loop',
  'multiple',
  'muted',
  'nomodule',
  'novalidate',
  'open',
  'playsinline',
  'required',
  'reversed',
  'selected',
];
export const COMPILE_TIME_HELPERS = ['has-block-params', 'has-block'];

export const BUILTIN_HELPERS = {
  'or': SYMBOLS.$__or,
  'and': SYMBOLS.$__and,
  'eq': SYMBOLS.$__eq,
  'not': SYMBOLS.$__not,
  'if': SYMBOLS.$__if,
  'debugger': `${SYMBOLS.$__debugger}.call`,
  'log': SYMBOLS.$__log,
  'array': SYMBOLS.$__array,
  'hash': SYMBOLS.$__hash,
  'fn': SYMBOLS.$__fn,
}