export type Flags = {
  IS_GLIMMER_COMPAT_MODE: boolean;
  IS_DEV_MODE: boolean;
  RUN_EVENT_DESTRUCTORS_FOR_SCOPED_NODES: boolean;
  TRY_CATCH_ERROR_HANDLING: boolean;
  SUPPORT_SHADOW_DOM: boolean;
  REACTIVE_MODIFIERS: boolean;
  WITH_HELPER_MANAGER: boolean;
  WITH_MODIFIER_MANAGER: boolean;
  WITH_EMBER_INTEGRATION: boolean;
  WITH_CONTEXT_API: boolean;
  ASYNC_COMPILE_TRANSFORMS: boolean;
};

export function defaultFlags() {
  return {
    IS_GLIMMER_COMPAT_MODE: true,
    RUN_EVENT_DESTRUCTORS_FOR_SCOPED_NODES: false,
    TRY_CATCH_ERROR_HANDLING: true,
    SUPPORT_SHADOW_DOM: true,
    REACTIVE_MODIFIERS: true,
    WITH_HELPER_MANAGER: false,
    WITH_MODIFIER_MANAGER: false,
    WITH_EMBER_INTEGRATION: false,
    WITH_CONTEXT_API: true,
    ASYNC_COMPILE_TRANSFORMS: true,
  } as Flags;
}
