export const SYMBOLS = {
  FINALIZE_COMPONENT: '$_fin',
  TAG: '$_tag',
  IF: '$_if',
  EACH: '$_each',
  EACH_SYNC: '$_eachSync',
  SLOT: '$_slot',
  EMPTY_DOM_PROPS: '$_edp',
  ARGS: '$_args',
  TEXT: '$_text',
  COMPONENT: '$_c',
  $SLOTS_SYMBOL: '$SLOTS_SYMBOL',
  $_GET_SLOTS: '$_GET_SLOTS',
  $_GET_ARGS: '$_GET_ARGS',
  $_GET_FW: '$_GET_FW',
  $template: '$template',
  $_hasBlockParams: '$_hasBlockParams',
  $_hasBlock: '$_hasBlock',
  $nodes: '$nodes',
  $args: '$args',
  $slotsProp: '$slotsProp',
  $propsProp: '$propsProp',
  $attrsProp: '$attrsProp',
  $_inElement: '$_inElement',
  $_ucw: '$_ucw',
  $eventsProp: '$eventsProp',
  $__if: '$__if',
  $__eq: '$__eq',
  $__debugger: '$__debugger',
  $__log: '$__log',
  $__array: '$__array',
  $__hash: '$__hash',
  $__fn: '$__fn',
};

export const EVENT_TYPE = {
  ON_CREATED: '0',
  TEXT_CONTENT: '1',
};

export const MAIN_IMPORT = '@lifeart/gxt';
