name: Coverage processing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  wait_for_data:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup pnpm
      uses: wyvox/action-setup-pnpm@v3
      with:
        node-version: "20.1.0"
    - name: Wait for Playwright tests
      continue-on-error: false
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-playwright-tests
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Playwright tests queue
        timeoutSeconds: 600
        intervalSeconds: 30
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Download Playwright test coverage artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        path: ./artifacts
        workflow: playwright.yaml
        workflow_conclusion: success
        name: playwright-coverage
        pr: ${{github.event.pull_request.number}}

    - name: Fix paths inside coverage reports
      run: node ./bin/fix-paths-in-coverage-reports.cjs

    - name: Merge all reported JSONs into one
      run: pnpm run ci:nyc:merge

    - name: Generate report
      run: pnpm run ci:nyc:report

    - name: Archive coverage report
      uses: vimtor/action-zip@v1
      with:
        files: ./coverage/lcov-report/
        dest: coverage.zip
    
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.zip
        retention-days: 1

    - name: Jest Lcov Reporter v2
      uses: lifeart/jest-lcov-reporter@v0.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        update-comment: true
        show-changed-files: false
        min-coverage: 1